services:
    auth.provider.django:
        class: modelbrouwers\authdjango\auth\provider\django
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }
